# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: MIT OR GPL-3.0-only
---
- name: Reload systemd
  sudo: yes
  command: systemctl daemon-reload
  notify:
    - Restart fleet

- name: Restart fleet
  service: name=fleet.service state=restarted
  sudo: yes
